### PR TITLE
Java object implementation

### PR DESCRIPTION
**Pull request by electro2560**
Work in progress of java object implementation for all Schoology objects and requests.

### CODE REVIEW

**Review by rvanasa — APPROVED** [review]

**Review by rvanasa — APPROVED** [review]
This looks awesome! Thanks for taking the time to implement this API properly. I updated the readme to give you additional credit.

**Comment by electro2560** [comment]
Thanks! I have a few more changes to make and then I'll mark this as ready to be merged.

**Comment by electro2560** [comment]
I'm still adding a few more objects, then this will be ready for merge

**Comment by electro2560** [comment]
Is having the API and implementation independent of each other necessary? I've created the schoology objects in the API module, but I've ran into a few problems moving forward. Inside the objects if I want to make additional calls to the request handler, I would need to use this complicated reference class and extend it. 
Screenshot from 2019-10-03 23-31-49
Screenshot from 2019-10-03 23-31-33
Then inside the request handler implementation, I need to pass the instance of the request handler so that additional requests can be made by the objects.
Screenshot from 2019-10-03 23-32-27
Then, using the user object as an example, I can get the request handler implementation instance and make my calls. Another problem is I'd like to use a JsonObject to set fields and easily create these put and post requests from the API module, but the GSON dependency should really only be located in the implementation module.
Screenshot from 2019-10-03 23-33-54

The other option would involve creating an InstanceCreator class in the implementation module for each schoology object so that a constructor with a reference to the requesthandler instance can be passed. The InstanceCreator won't work with a parent class which could contain the requesthandler reference. This would also be redundant like treating these schoology objects as abstract or an interface in the API and writing an implementation for each one.

Should we remove the API module and just focus on the implementation?


Please let me know if you have any other ideas on how we could solve this. I think having a separate API and impl module may be complicating things at this point and isn't necessary.

**Comment by rvanasa** [comment]
The distinction between the API and implementation modules is very arbitrary, since I had originally intended to take a completely different direction with the project. I would definitely be up for dropping the "API" abstraction in favor of a more consolidated architecture. 

Thank you again for your fantastic work on this project.

**Pull request merged**
